website: http://marcely.de
version: "1.4"
name: BedwarsHub
author: Marcely1199
main: com.grassminevn.bwhub.BedwarsHub
description: Bedwars is a minigame
commands:
  bw:
    description: Bedwars is a minigame
    usage: /bw
    aliases: [bedwars, bedwar]
permissions:
  bw.*:
    default: op
    children:
    - bw_summon
    - bw_list
    - bw_info
    - bw_join
    - bw_beta
  bw.summon:
    default: op
  bw.list:
    default: op
  bw.info:
    default: op
  bw.join:
    default: op
  bw.beta:
    default: op